/**
 * SERAG FRAGRANCES Catalog & Data Store
 * All Authentic Products, High-Resolution Real Product Images & Verified Pricing
 */

const SERAG_CATALOG_VERSION = "v2_serag_real_images_2026_09";

const DEFAULT_PRODUCTS = [
  {
    "id": 1,
    "slug": "shiny",
    "nameEn": "Shiny",
    "nameAr": "شايني",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Floral & Fresh Amber",
    "topNotes": "Bergamot, Solar Notes",
    "heartNotes": "Solar Amber, Jasmine",
    "baseNotes": "White Musk, Cedar",
    "shape": "shine",
    "badge": "Bestseller",
    "themeColor": "#0A192F",
    "rating": 4.9,
    "reviewsCount": 48,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/shiny.jpg",
    "customImage": null
  },
  {
    "id": 2,
    "slug": "crown-black",
    "nameEn": "Crown Black",
    "nameAr": "كراون بلاك",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Royal Woody Oud",
    "topNotes": "Cardamom, Black Pepper",
    "heartNotes": "Smoky Incense, Birch Wood",
    "baseNotes": "Royal Agarwood, Dark Leather",
    "shape": "crown",
    "badge": "VIP Choice",
    "themeColor": "#0A192F",
    "rating": 4.9,
    "reviewsCount": 52,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/crown-black.jpg",
    "customImage": null
  },
  {
    "id": 3,
    "slug": "la-bella",
    "nameEn": "La Bella",
    "nameAr": "لا بيلا",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Gourmand Floral",
    "topNotes": "Sweet Pear, Blossom",
    "heartNotes": "Florentine Iris, Jasmine",
    "baseNotes": "Madagascar Vanilla, Praline",
    "shape": "rose",
    "badge": "Trending",
    "themeColor": "#D48C9E",
    "rating": 4.9,
    "reviewsCount": 39,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/la-bella.jpg",
    "customImage": null
  },
  {
    "id": 4,
    "slug": "aura",
    "nameEn": "Aura",
    "nameAr": "اورا",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Powdery Citrus",
    "topNotes": "Italian Lemon, Bergamot",
    "heartNotes": "French Iris, Violet",
    "baseNotes": "White Sandalwood, Musk",
    "shape": "crystal",
    "badge": "Classic",
    "themeColor": "#8BA4C4",
    "rating": 4.9,
    "reviewsCount": 42,
    "inStock": true,
    "stockCount": 40,
    "image": null,
    "customImage": null
  },
  {
    "id": 5,
    "slug": "khayal",
    "nameEn": "Khayal",
    "nameAr": "خيال",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Mystic Oriental Incense",
    "topNotes": "Rare Saffron, Nutmeg",
    "heartNotes": "Smoky Olibanum, Labdanum",
    "baseNotes": "Imperial Oud, Golden Amber",
    "shape": "gold",
    "badge": "Signature",
    "themeColor": "#0A192F",
    "rating": 4.9,
    "reviewsCount": 45,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/khayal.jpg",
    "customImage": null
  },
  {
    "id": 6,
    "slug": "dubai-sky",
    "nameEn": "Dubai Sky",
    "nameAr": "دبي اسكاي",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Modern Amber Leather",
    "topNotes": "Crisp Apple, Cardamom",
    "heartNotes": "Taif Rose, Geranium",
    "baseNotes": "Ambergris, Rich Leather",
    "shape": "blue",
    "badge": "Popular",
    "themeColor": "#002B49",
    "rating": 4.9,
    "reviewsCount": 48,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/dubai-sky.jpg",
    "customImage": null
  },
  {
    "id": 7,
    "slug": "abu-dhabi-sky",
    "nameEn": "Abu Dhabi Sky",
    "nameAr": "ابو ظبي اسكاي",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Imperial Oud & Amber",
    "topNotes": "Golden Citrus, Saffron",
    "heartNotes": "Arabian Rose, Incense",
    "baseNotes": "Aged Oud, Sandalwood",
    "shape": "royal",
    "badge": "Royal Edition",
    "themeColor": "#7851A9",
    "rating": 4.9,
    "reviewsCount": 51,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/abu-dhabi-sky.jpg",
    "customImage": null
  },
  {
    "id": 8,
    "slug": "doha-sky",
    "nameEn": "Doha Sky",
    "nameAr": "دوحه اسكاي",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Warm Amber Tonka",
    "topNotes": "Cinnamon, Bergamot",
    "heartNotes": "Tonka Bean, Roasted Praline",
    "baseNotes": "Golden Amber, Patchouli",
    "shape": "amber",
    "badge": "New",
    "themeColor": "#B87333",
    "rating": 4.9,
    "reviewsCount": 54,
    "inStock": true,
    "stockCount": 40,
    "image": "assets/images/doha-sky.jpg",
    "customImage": null
  },
  {
    "id": 9,
    "slug": "zayed",
    "nameEn": "Zayed",
    "nameAr": "زايد",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Regal Heritage Oud",
    "topNotes": "Royal Saffron, Bergamot",
    "heartNotes": "Damascena Rose, Amber",
    "baseNotes": "Cambodian Oud, Musk",
    "shape": "crown",
    "badge": "Legendary",
    "themeColor": "#0A192F",
    "rating": 4.9,
    "reviewsCount": 57,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/zayed.jpg",
    "customImage": null
  },
  {
    "id": 10,
    "slug": "master",
    "nameEn": "Master",
    "nameAr": "ماستر",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Aromatic Woody Vetiver",
    "topNotes": "Bergamot, Grapefruit",
    "heartNotes": "Haitian Vetiver, Pink Pepper",
    "baseNotes": "Dark Amber, Oakmoss",
    "shape": "black",
    "badge": "Executive",
    "themeColor": "#1A2A3A",
    "rating": 4.9,
    "reviewsCount": 60,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/master.jpg",
    "customImage": null
  },
  {
    "id": 11,
    "slug": "signature-rose-gold",
    "nameEn": "Signature Rose Gold",
    "nameAr": "سجنتشر روز جولد",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Rose & Sweet Praline",
    "topNotes": "Pink Champagne, Lychee",
    "heartNotes": "Velvet Damask Rose, Praline",
    "baseNotes": "Bourbon Vanilla, Cashmeran",
    "shape": "rose",
    "badge": "Exclusive",
    "themeColor": "#B76E79",
    "rating": 4.9,
    "reviewsCount": 63,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/signature-rose-gold.jpg",
    "customImage": null
  },
  {
    "id": 12,
    "slug": "signature-gold",
    "nameEn": "Signature Gold",
    "nameAr": "سجنتشر جولد",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Precious Amber & Saffron",
    "topNotes": "Golden Saffron, Bergamot",
    "heartNotes": "Honeyed Amber, Cinnamon",
    "baseNotes": "Royal Agarwood, Musk",
    "shape": "gold",
    "badge": "Exclusive",
    "themeColor": "#0A192F",
    "rating": 4.9,
    "reviewsCount": 66,
    "inStock": true,
    "stockCount": 40,
    "image": "assets/images/signature-gold.jpg",
    "customImage": null
  },
  {
    "id": 13,
    "slug": "signature-silver",
    "nameEn": "Signature Silver",
    "nameAr": "سجنتشر سيلفر",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Fresh Silver Musk",
    "topNotes": "Cool Mint, Calabrian Lemon",
    "heartNotes": "French Lavender, Clary Sage",
    "baseNotes": "Silver Cedar, White Amber",
    "shape": "silver",
    "badge": "Exclusive",
    "themeColor": "#A8A9AD",
    "rating": 4.9,
    "reviewsCount": 69,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/signature-silver.jpg",
    "customImage": null
  },
  {
    "id": 14,
    "slug": "signature-white",
    "nameEn": "Signature White",
    "nameAr": "سجنتشر وايت",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Pure White Flowers",
    "topNotes": "White Freesia, Water Lily",
    "heartNotes": "Lily of Valley, Jasmine",
    "baseNotes": "Powdery Musk, Sandalwood",
    "shape": "white",
    "badge": "Exclusive",
    "themeColor": "#EAEAEA",
    "rating": 4.9,
    "reviewsCount": 32,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/signature-white.jpg",
    "customImage": null
  },
  {
    "id": 15,
    "slug": "vanilla-wood",
    "nameEn": "Vanilla Wood",
    "nameAr": "فانيلا وود",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Smoky Bourbon Vanilla",
    "topNotes": "Crushed Almond, Orchid",
    "heartNotes": "Madagascar Vanilla, Heliotrope",
    "baseNotes": "Smoky Guaiac Wood, Cedar",
    "shape": "wood",
    "badge": "Bestseller",
    "themeColor": "#8D5B4C",
    "rating": 4.9,
    "reviewsCount": 35,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/vanilla-wood.jpg",
    "customImage": null
  },
  {
    "id": 16,
    "slug": "al-hilal-5",
    "nameEn": "Al-Hilal 5",
    "nameAr": "الهلال ٥",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Spiced Lavender Oud",
    "topNotes": "Cardamom, Lavender",
    "heartNotes": "Cashmere Wood, Nutmeg",
    "baseNotes": "Oud Wood, Earthy Vetiver",
    "shape": "blue",
    "badge": "Collector",
    "themeColor": "#0D3B66",
    "rating": 4.9,
    "reviewsCount": 38,
    "inStock": true,
    "stockCount": 40,
    "image": "assets/images/al-hilal-5.jpg",
    "customImage": null
  },
  {
    "id": 17,
    "slug": "al-hilal-37",
    "nameEn": "Al-Hilal 37",
    "nameAr": "الهلال ٣٧",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Tobacco Cinnamon Spiced",
    "topNotes": "Spiced Cinnamon, Aged Rum",
    "heartNotes": "Cured Tobacco, Dark Honey",
    "baseNotes": "Spiced Amber, Tonka",
    "shape": "tobacco",
    "badge": "Collector",
    "themeColor": "#5C2C16",
    "rating": 4.9,
    "reviewsCount": 41,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/al-hilal-37.jpg",
    "customImage": null
  },
  {
    "id": 18,
    "slug": "al-hilal-8",
    "nameEn": "Al-Hilal 8",
    "nameAr": "الهلال ٨",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Citrus Fresh Marine",
    "topNotes": "Green Apple, Bergamot",
    "heartNotes": "Rosemary, Marine Ozone",
    "baseNotes": "Royal Oakmoss, Clean Amber",
    "shape": "cyan",
    "badge": "Collector",
    "themeColor": "#006D77",
    "rating": 4.9,
    "reviewsCount": 44,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/al-hilal-8.jpg",
    "customImage": null
  },
  {
    "id": 19,
    "slug": "no-one",
    "nameEn": "No One",
    "nameAr": "نو ون",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Mysterious Tea Leather",
    "topNotes": "Smoked Black Tea, Bergamot",
    "heartNotes": "Dark Leather, Violet",
    "baseNotes": "Black Amber, Patchouli",
    "shape": "black",
    "badge": "Intense",
    "themeColor": "#111827",
    "rating": 4.9,
    "reviewsCount": 47,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/no-one.jpg",
    "customImage": null
  },
  {
    "id": 20,
    "slug": "haneet",
    "nameEn": "Haneet",
    "nameAr": "حنيت",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Smoky Clove Agarwood",
    "topNotes": "Clove Bud, Cardamom",
    "heartNotes": "Smoky Frankincense, Birch Tar",
    "baseNotes": "Aged Oud, Dark Resin",
    "shape": "amber",
    "badge": "Traditional",
    "themeColor": "#7B3F00",
    "rating": 4.9,
    "reviewsCount": 50,
    "inStock": true,
    "stockCount": 40,
    "image": "assets/images/haneet.jpg",
    "customImage": null
  },
  {
    "id": 21,
    "slug": "so-sweety",
    "nameEn": "So Sweety",
    "nameAr": "سو سويتي",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Gourmand Berry Caramel",
    "topNotes": "Red Berries, Sugar Cane",
    "heartNotes": "Salted Caramel, Marshmallow",
    "baseNotes": "Vanilla Cream, Sweet Tonka",
    "shape": "pink",
    "badge": "Favorite",
    "themeColor": "#E05A87",
    "rating": 4.9,
    "reviewsCount": 53,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/so-sweety.jpg",
    "customImage": null
  },
  {
    "id": 22,
    "slug": "dokhoon-leather",
    "nameEn": "Dokhoon Leather",
    "nameAr": "دخون ليذر",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Tuscan Leather & Raspberry",
    "topNotes": "Wild Thyme, Saffron",
    "heartNotes": "Tuscan Leather, Raspberry",
    "baseNotes": "Night Jasmine, Amber",
    "shape": "leather",
    "badge": "Bestseller",
    "themeColor": "#4A2C2A",
    "rating": 4.9,
    "reviewsCount": 56,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/dokhoon-leather.jpg",
    "customImage": null
  },
  {
    "id": 23,
    "slug": "dokhoon-desert",
    "nameEn": "Dokhoon Desert",
    "nameAr": "دخون ديزرت",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Desert Rose & Sandalwood",
    "topNotes": "Desert Sun Accord, Mandarin",
    "heartNotes": "Taif Rose, Cinnamon",
    "baseNotes": "Warm Sandalwood, Golden Amber",
    "shape": "gold",
    "badge": "Signature",
    "themeColor": "#D4A373",
    "rating": 4.9,
    "reviewsCount": 59,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/dokhoon-desert.jpg",
    "customImage": null
  },
  {
    "id": 24,
    "slug": "khalifa",
    "nameEn": "Khalifa",
    "nameAr": "خليفه",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Imperial Saffron Oud",
    "topNotes": "Imperial Saffron, Cardamom",
    "heartNotes": "Royal Taif Rose, Amber",
    "baseNotes": "Vintage Agarwood, Musk",
    "shape": "crown",
    "badge": "Prestige",
    "themeColor": "#B38B38",
    "rating": 4.9,
    "reviewsCount": 62,
    "inStock": true,
    "stockCount": 40,
    "image": "assets/images/khalifa.jpg",
    "customImage": null
  },
  {
    "id": 25,
    "slug": "dokhoon-rose",
    "nameEn": "Dokhoon Rose",
    "nameAr": "دخون روز",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Dewy Velvet Rose",
    "topNotes": "Morning Dew, Sweet Lychee",
    "heartNotes": "Velvet Damask Rose, Peony",
    "baseNotes": "White Amber, Soft Cedar",
    "shape": "rose",
    "badge": "Romantic",
    "themeColor": "#C94C7A",
    "rating": 4.9,
    "reviewsCount": 65,
    "inStock": true,
    "stockCount": 45,
    "image": "assets/images/dokhoon-rose.jpg",
    "customImage": null
  },
  {
    "id": 26,
    "slug": "private-2-december",
    "nameEn": "Private 2 December",
    "nameAr": "برايفت ٢ ديسيمبر",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "National Pride Amber Oud",
    "topNotes": "Arabian Jasmine, Bergamot",
    "heartNotes": "Precious Saffron, Frankincense",
    "baseNotes": "Royal Agarwood, Golden Amber",
    "shape": "gold",
    "badge": "Limited",
    "themeColor": "#997A15",
    "rating": 4.9,
    "reviewsCount": 68,
    "inStock": true,
    "stockCount": 50,
    "image": "assets/images/private-2-december.jpg",
    "customImage": null
  },
  {
    "id": 27,
    "slug": "ti-amo",
    "nameEn": "Ti Amo",
    "nameAr": "تيامو",
    "category": "dokhoony",
    "categoryNameEn": "Dokhoony Collection",
    "categoryNameAr": "قسم دخوني",
    "price": 1700,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Sensual Floral Musk",
    "topNotes": "Sparkling Peach, Mandarin",
    "heartNotes": "Romantic Peony, Damask Rose",
    "baseNotes": "Sensual White Musk, Vanilla",
    "shape": "pink",
    "badge": "Romantic",
    "themeColor": "#D15A75",
    "rating": 4.9,
    "reviewsCount": 31,
    "inStock": true,
    "stockCount": 55,
    "image": "assets/images/ti-amo.jpg",
    "customImage": null
  },
  {
    "id": 28,
    "slug": "emerald-soul",
    "nameEn": "Emerald Soul",
    "nameAr": "ايمرلد سول",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Green Aromatic Fresh",
    "topNotes": "Crisp Mint, Green Apple",
    "heartNotes": "Lavender, Violet Leaf",
    "baseNotes": "Haitian Vetiver, Patchouli",
    "shape": "emerald",
    "badge": "Iconic",
    "themeColor": "#0F5257",
    "rating": 4.9,
    "reviewsCount": 57,
    "inStock": true,
    "stockCount": 42,
    "image": "assets/images/emerald-soul.jpeg",
    "customImage": null
  },
  {
    "id": 29,
    "slug": "note-coral",
    "nameEn": "Note Coral",
    "nameAr": "نوت كورال",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Solar Coral Floral",
    "topNotes": "Sunlit Citrus, Coral Blossom",
    "heartNotes": "Wild Orchid, Solar Jasmine",
    "baseNotes": "Amber Crystals, Soft Cedar",
    "shape": "coral",
    "badge": "Vibrant",
    "themeColor": "#F07167",
    "rating": 4.9,
    "reviewsCount": 61,
    "inStock": true,
    "stockCount": 46,
    "image": "assets/images/note-coral.jpeg",
    "customImage": null
  },
  {
    "id": 30,
    "slug": "black-diamond-incense",
    "nameEn": "Black Diamond Incense",
    "nameAr": "بلاك دايموند انسنس",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Dark Smoky Incense Oud",
    "topNotes": "Smoky Frankincense, Cardamom",
    "heartNotes": "Dark Labdanum, Rich Incense",
    "baseNotes": "Black Agarwood, Leather",
    "shape": "black",
    "badge": "VIP",
    "themeColor": "#1C1D21",
    "rating": 5.0,
    "reviewsCount": 65,
    "inStock": true,
    "stockCount": 30,
    "image": "assets/images/black-diamond-incense.jpeg",
    "customImage": null
  },
  {
    "id": 31,
    "slug": "blue-diamond-aqua",
    "nameEn": "Blue Diamond Aqua",
    "nameAr": "بلو دايموند اكوا",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Deep Marine Ozone",
    "topNotes": "Marine Ozone, Grapefruit",
    "heartNotes": "Sea Salt, Driftwood, Sage",
    "baseNotes": "Ambergris, Coastal Cedar",
    "shape": "blue",
    "badge": "Fresh",
    "themeColor": "#0B4F6C",
    "rating": 5.0,
    "reviewsCount": 69,
    "inStock": true,
    "stockCount": 34,
    "image": "assets/images/blue-diamond-aqua.jpg",
    "customImage": null
  },
  {
    "id": 32,
    "slug": "white-regent",
    "nameEn": "White Regent",
    "nameAr": "وايت ريجنت",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Royal White Suede Iris",
    "topNotes": "White Pepper, Bergamot",
    "heartNotes": "Florentine Orris, White Suede",
    "baseNotes": "Clean White Musk, Cashmere",
    "shape": "white",
    "badge": "Pure Luxury",
    "themeColor": "#F4F4F9",
    "rating": 4.9,
    "reviewsCount": 73,
    "inStock": true,
    "stockCount": 38,
    "image": "assets/images/white-regent.jpg",
    "customImage": null
  },
  {
    "id": 33,
    "slug": "black-carbon",
    "nameEn": "Black Carbon",
    "nameAr": "بلاك كاربون",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Smoky Mineral Amber",
    "topNotes": "Cardamom, Mineral Accord",
    "heartNotes": "Burnt Amber, Gunpowder Smoke",
    "baseNotes": "Dark Exotic Woods, Vetiver",
    "shape": "carbon",
    "badge": "Bold",
    "themeColor": "#2B2D42",
    "rating": 4.9,
    "reviewsCount": 77,
    "inStock": true,
    "stockCount": 42,
    "image": "assets/images/black-carbon.jpg",
    "customImage": null
  },
  {
    "id": 34,
    "slug": "plus-rose",
    "nameEn": "Plus Rose",
    "nameAr": "بلس روز",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Intense Bulgarian Rose",
    "topNotes": "Pink Pepper, Sweet Lychee",
    "heartNotes": "Bulgarian Rose Absolute, Raspberry",
    "baseNotes": "Ambergris, Silk Musk",
    "shape": "rose",
    "badge": "Special",
    "themeColor": "#A4133C",
    "rating": 4.9,
    "reviewsCount": 36,
    "inStock": true,
    "stockCount": 46,
    "image": "assets/images/plus-rose.jpg",
    "customImage": null
  },
  {
    "id": 35,
    "slug": "purple-heart",
    "nameEn": "Purple Heart",
    "nameAr": "بربل هارت",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Dark Plum & Orchid",
    "topNotes": "Dark Plum, Black Cherry",
    "heartNotes": "Night Orchid, Tonka Bean",
    "baseNotes": "Velvet Musk, Dark Amber",
    "shape": "purple",
    "badge": "Sensual",
    "themeColor": "#4A154B",
    "rating": 4.9,
    "reviewsCount": 40,
    "inStock": true,
    "stockCount": 30,
    "image": "assets/images/purple-heart.jpg",
    "customImage": null
  },
  {
    "id": 36,
    "slug": "pink-diamond-sakura",
    "nameEn": "Pink Diamond Sakura",
    "nameAr": "بينك دايموند ساكورا",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Japanese Cherry Blossom",
    "topNotes": "Cherry Blossom, Mandarin",
    "heartNotes": "White Tea, Freesia",
    "baseNotes": "Silk Musk, Hinoki Wood",
    "shape": "pink",
    "badge": "Delicate",
    "themeColor": "#F4978E",
    "rating": 5.0,
    "reviewsCount": 44,
    "inStock": true,
    "stockCount": 34,
    "image": "assets/images/pink-diamond-sakura.jpg",
    "customImage": null
  },
  {
    "id": 37,
    "slug": "french-tobacco",
    "nameEn": "French Tobacco",
    "nameAr": "فرينش توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Blonde Honeyed Tobacco",
    "topNotes": "Aged Cognac, Sweet Plum",
    "heartNotes": "Parisian Blonde Tobacco, Honey",
    "baseNotes": "Bourbon Vanilla, French Cedar",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#7F4F24",
    "rating": 5.0,
    "reviewsCount": 48,
    "inStock": true,
    "stockCount": 38,
    "image": "assets/images/french-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 38,
    "slug": "spanish-tobacco",
    "nameEn": "Spanish Tobacco",
    "nameAr": "اسبانيش توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Seville Leather Tobacco",
    "topNotes": "Seville Orange, Nutmeg",
    "heartNotes": "Dark Spanish Tobacco, Leather",
    "baseNotes": "Smoky Amber, Spanish Oakwood",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#6B3E26",
    "rating": 5.0,
    "reviewsCount": 52,
    "inStock": true,
    "stockCount": 42,
    "image": "assets/images/spanish-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 39,
    "slug": "arabian-tobacco",
    "nameEn": "Arabian Tobacco",
    "nameAr": "اريبان توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Spiced Saffron Tobacco Oud",
    "topNotes": "Arabian Spices, Saffron",
    "heartNotes": "Cured Pipe Tobacco, Taif Rose",
    "baseNotes": "Cambodian Agarwood, Amber",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#582F0E",
    "rating": 5.0,
    "reviewsCount": 56,
    "inStock": true,
    "stockCount": 46,
    "image": "assets/images/arabian-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 40,
    "slug": "greek-tobacco",
    "nameEn": "Greek Tobacco",
    "nameAr": "جرك توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Aegean Sun & Fig Tobacco",
    "topNotes": "Fig Leaf, Bergamot",
    "heartNotes": "Aegean Sun Tobacco, Wild Honey",
    "baseNotes": "Olive Wood, Golden Amber",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#704620",
    "rating": 5.0,
    "reviewsCount": 60,
    "inStock": true,
    "stockCount": 30,
    "image": "assets/images/greek-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 41,
    "slug": "mexican-tobacco",
    "nameEn": "Mexican Tobacco",
    "nameAr": "ميكسكن توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Roasted Cacao Spiced Tobacco",
    "topNotes": "Roasted Cacao, Cinnamon",
    "heartNotes": "Spiced Mexican Tobacco, Vanilla",
    "baseNotes": "Smoky Balsam, Dark Amber",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#4A2810",
    "rating": 5.0,
    "reviewsCount": 64,
    "inStock": true,
    "stockCount": 34,
    "image": "assets/images/mexican-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 42,
    "slug": "dominican-tobacco",
    "nameEn": "Dominican Tobacco",
    "nameAr": "دومنيكن توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Caribbean Cigar & Rum",
    "topNotes": "Dark Rum, Nutmeg",
    "heartNotes": "Premium Cigar Leaf, Tonka",
    "baseNotes": "Honduran Cedar, Ambergris",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#3D1E06",
    "rating": 5.0,
    "reviewsCount": 68,
    "inStock": true,
    "stockCount": 38,
    "image": "assets/images/dominican-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 43,
    "slug": "jamaican-tobacco",
    "nameEn": "Jamaican Tobacco",
    "nameAr": "جامايكان توباكو",
    "category": "abraaq",
    "categoryNameEn": "Abraaq Collection",
    "categoryNameAr": "قسم أبرق",
    "price": 1850,
    "volume": "100ml / 3.4 fl oz",
    "scentFamily": "Exotic Caribbean Spiced Tobacco",
    "topNotes": "Jamaican Allspice, Blood Orange",
    "heartNotes": "Aged Tobacco Leaf, Sugarcane",
    "baseNotes": "Smoked Cedar, Dark Vanilla",
    "shape": "tobacco",
    "badge": "Masterpiece",
    "themeColor": "#5A2A18",
    "rating": 5.0,
    "reviewsCount": 35,
    "inStock": true,
    "stockCount": 30,
    "image": "assets/images/jamaican-tobacco.jpg",
    "customImage": null
  },
  {
    "id": 44,
    "slug": "diamond-collection-blue-red-white",
    "nameEn": "Diamond Collection (Blue, Red, White)",
    "nameAr": "دايموند كوليكشن (أزرق، أحمر، أبيض)",
    "category": "special",
    "categoryNameEn": "Special Gift Sets",
    "categoryNameAr": "المجموعات الملكية والبوكسات",
    "price": 2600,
    "volume": "3 x 50ml (Trio Box)",
    "scentFamily": "Royal Trio Box (3 x 50ml)",
    "topNotes": "Precious Saffron, Bergamot, Pepper",
    "heartNotes": "Taif Rose, Blue Lotus, Orris",
    "baseNotes": "Royal Agarwood, Ambergris, Cashmeran",
    "shape": "diamond",
    "badge": "Royal Set",
    "themeColor": "#0A192F",
    "rating": 5.0,
    "reviewsCount": 146,
    "inStock": true,
    "stockCount": 18,
    "image": "assets/images/diamond-collection-blue-red-white.jpg",
    "customImage": null
  },
  {
    "id": 45,
    "slug": "diamond-collection-box-6-pieces-x-10ml",
    "nameEn": "Diamond Collection Box (6 Pieces x 10ml)",
    "nameAr": "دايموند كوليكشن ٦ قطع ١٠ ملي",
    "category": "special",
    "categoryNameEn": "Special Gift Sets",
    "categoryNameAr": "المجموعات الملكية والبوكسات",
    "price": 1500,
    "volume": "6 x 10ml (Discovery Box)",
    "scentFamily": "Discovery Travel Box (6 x 10ml)",
    "topNotes": "Assorted Top Fragrance Selection",
    "heartNotes": "Floral, Spice & Incense Hearts",
    "baseNotes": "Rich Oud & Amber Foundations",
    "shape": "box",
    "badge": "Gift Edition",
    "themeColor": "#0A192F",
    "rating": 5.0,
    "reviewsCount": 148,
    "inStock": true,
    "stockCount": 18,
    "image": "assets/images/diamond-collection-box-6-pieces-x-10ml.jpg",
    "customImage": null
  },
  {
    "id": 46,
    "slug": "tobacco-box-9-pieces-x-20ml",
    "nameEn": "Tobacco Box (9 Pieces x 20ml)",
    "nameAr": "بوكس التوباكو ٩ قطع في ٢٠ ملي",
    "category": "special",
    "categoryNameEn": "Special Gift Sets",
    "categoryNameAr": "المجموعات الملكية والبوكسات",
    "price": 3200,
    "volume": "9 x 20ml (Master Collector)",
    "scentFamily": "Ultimate Tobacco Collector (9 x 20ml)",
    "topNotes": "All 6 Global Tobacco Editions + 3 Blends",
    "heartNotes": "Cured Tobacco, Cognac, Cacao, Honey",
    "baseNotes": "Smoked Woods, Balsams, Aged Agarwood",
    "shape": "tobacco_box",
    "badge": "Master Box",
    "themeColor": "#7F4F24",
    "rating": 5.0,
    "reviewsCount": 150,
    "inStock": true,
    "stockCount": 18,
    "image": "assets/images/tobacco-box-9-pieces-x-20ml.jpg",
    "customImage": null
  }
];

function getBottleSVG(product) {
  const imgSrc = product.customImage || product.image;
  
  if (imgSrc && !imgSrc.endsWith('.svg') && !imgSrc.includes('assets/images/shiny.png') && !imgSrc.includes('assets/images/aura.png')) {
    return `<div class="bottle-image-container relative w-full h-[220px] flex items-center justify-center overflow-hidden rounded-2xl p-2 bg-[#F8FAFC] dark:via-slate-900/40 dark:to-slate-950/60">
      <img src="${imgSrc}" alt="${product.nameEn}" class="bottle-real-img max-h-full max-w-full object-contain drop-shadow-2xl transition-all duration-500 group-hover:scale-105 group-hover:drop-shadow-[0_15px_25px_rgba(212,175,55,0.25)]" loading="lazy" onerror="this.parentElement.innerHTML = getFallbackBottleSVG(window.seragApp ? window.seragApp.getProductById(${product.id}) : null);" />
    </div>`;
  }
  
  return getFallbackBottleSVG(product);
}

function getFallbackBottleSVG(product) {
  if (!product) product = { nameAr: "سراج", themeColor: "#0A192F", id: 99 };
  const color = product.themeColor || '#0A192F';
  const isDark = product.themeColor === '#0A192F' || product.themeColor === '#1C1D21' || product.themeColor === '#111827';
  
  if (product.shape === 'tobacco_box' || product.shape === 'box') {
    return '<svg class="bottle-svg" viewBox="0 0 200 240" xmlns="http://www.w3.org/2000/svg">' +
      '<defs>' +
      '<linearGradient id="boxGrad-' + product.id + '" x1="0%" y1="0%" x2="100%" y2="100%">' +
      '<stop offset="0%" stop-color="#1E1E24"/>' +
      '<stop offset="50%" stop-color="#0A192F"/>' +
      '<stop offset="100%" stop-color="#001B30"/>' +
      '</linearGradient>' +
      '<linearGradient id="goldBorder-' + product.id + '" x1="0%" y1="0%" x2="100%" y2="100%">' +
      '<stop offset="0%" stop-color="#FFFFFF"/>' +
      '<stop offset="50%" stop-color="#0A192F"/>' +
      '<stop offset="100%" stop-color="#0A192F"/>' +
      '</linearGradient>' +
      '</defs>' +
      '<rect x="25" y="45" width="150" height="160" rx="8" fill="url(#boxGrad-' + product.id + ')" stroke="url(#goldBorder-' + product.id + ')" stroke-width="3"/>' +
      '<rect x="35" y="55" width="130" height="140" rx="5" fill="none" stroke="url(#goldBorder-' + product.id + ')" stroke-width="1" stroke-dasharray="3,3"/>' +
      '<rect x="55" y="95" width="90" height="60" rx="4" fill="#001424" stroke="url(#goldBorder-' + product.id + ')" stroke-width="1.5"/>' +
      '<circle cx="100" cy="115" r="12" fill="none" stroke="#0A192F" stroke-width="1.5"/>' +
      '<path d="M96,115 L104,115 M100,110 L100,120" stroke="#0A192F" stroke-width="1.5" stroke-linecap="round"/>' +
      '<text x="100" y="142" text-anchor="middle" fill="#0A192F" font-size="9" font-family="Cinzel, serif" font-weight="bold" letter-spacing="1.5">SERAG</text>' +
      '<text x="100" y="182" text-anchor="middle" fill="#FFFFFF" font-size="8" font-family="Cairo, sans-serif">' + (product.nameAr || '') + '</text>' +
      '</svg>';
  }

  return '<svg class="bottle-svg" viewBox="0 0 180 260" xmlns="http://www.w3.org/2000/svg">' +
    '<defs>' +
    '<linearGradient id="glassGrad-' + product.id + '" x1="0%" y1="0%" x2="100%" y2="0%">' +
    '<stop offset="0%" stop-color="rgba(255,255,255,0.7)"/>' +
    '<stop offset="20%" stop-color="rgba(255,255,255,0.3)"/>' +
    '<stop offset="80%" stop-color="rgba(255,255,255,0.1)"/>' +
    '<stop offset="100%" stop-color="rgba(255,255,255,0.6)"/>' +
    '</linearGradient>' +
    '<linearGradient id="liquidGrad-' + product.id + '" x1="0%" y1="0%" x2="100%" y2="100%">' +
    '<stop offset="0%" stop-color="' + color + '" stop-opacity="0.85"/>' +
    '<stop offset="100%" stop-color="' + (isDark ? '#001424' : '#6A4315') + '" stop-opacity="0.95"/>' +
    '</linearGradient>' +
    '<linearGradient id="goldCap-' + product.id + '" x1="0%" y1="0%" x2="100%" y2="0%">' +
    '<stop offset="0%" stop-color="#B38728"/>' +
    '<stop offset="30%" stop-color="#FBF5B7"/>' +
    '<stop offset="60%" stop-color="#DAA520"/>' +
    '<stop offset="100%" stop-color="#AA771C"/>' +
    '</linearGradient>' +
    '</defs>' +
    '<path d="M72,15 L108,15 L104,42 L76,42 Z" fill="url(#goldCap-' + product.id + ')" stroke="#0A192F" stroke-width="0.8"/>' +
    '<rect x="78" y="42" width="24" height="12" rx="1" fill="url(#goldCap-' + product.id + ')"/>' +
    '<path d="M50,75 C50,56 70,54 80,54 L100,54 C110,54 130,56 130,75 L132,215 C132,230 120,235 105,235 L75,235 C60,235 48,230 48,215 Z" fill="url(#liquidGrad-' + product.id + ')" stroke="url(#glassGrad-' + product.id + ')" stroke-width="3.5"/>' +
    '<path d="M56,80 L56,212 C56,222 65,225 78,225" fill="none" stroke="rgba(255,255,255,0.65)" stroke-width="2.5" stroke-linecap="round"/>' +
    '<rect x="60" y="110" width="60" height="75" rx="4" fill="#0A192F" stroke="url(#goldCap-' + product.id + ')" stroke-width="1.5"/>' +
    '<rect x="64" y="114" width="52" height="67" rx="2" fill="none" stroke="#0A192F" stroke-width="0.7" stroke-dasharray="2,2"/>' +
    '<text x="90" y="135" text-anchor="middle" fill="#0A192F" font-size="8" font-family="Cinzel, serif" font-weight="bold" letter-spacing="1">SERAG</text>' +
    '<text x="90" y="148" text-anchor="middle" fill="#FFFFFF" font-size="6.5" font-family="Cairo, sans-serif" font-weight="bold">' + (product.nameAr || '') + '</text>' +
    '<text x="90" y="162" text-anchor="middle" fill="#FFFFFF" font-size="5" font-family="Plus Jakarta Sans, sans-serif" letter-spacing="0.5">EAU DE PARFUM</text>' +
    '<text x="90" y="173" text-anchor="middle" fill="#0A192F" font-size="5" font-family="Cinzel, serif">100 ML</text>' +
    '</svg>';
}

function getProductsCatalog() {
  try {
    const currentVer = localStorage.getItem('serag_catalog_version');
    if (currentVer !== SERAG_CATALOG_VERSION) {
      localStorage.setItem('serag_catalog_version', SERAG_CATALOG_VERSION);
      localStorage.setItem('serag_fragrances_catalog', JSON.stringify(DEFAULT_PRODUCTS));
      return DEFAULT_PRODUCTS;
    }
    
    const saved = localStorage.getItem('serag_fragrances_catalog');
    if (saved) {
      return JSON.parse(saved);
    }
  } catch (e) {
    console.error('Failed to parse saved catalog:', e);
  }
  return DEFAULT_PRODUCTS;
}

function saveProductsCatalog(products) {
  localStorage.setItem('serag_fragrances_catalog', JSON.stringify(products));
}

function resetProductsCatalog() {
  localStorage.setItem('serag_catalog_version', SERAG_CATALOG_VERSION);
  localStorage.setItem('serag_fragrances_catalog', JSON.stringify(DEFAULT_PRODUCTS));
  return DEFAULT_PRODUCTS;
}
